my_blog/article/urls.py
# 引入path
from django.urls import path
# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    # 左：请求地址/中：视图方法/右：网页内部调用
    path('article_list/',views.article_list,name='article_list'),
    # 文章详情
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    # 新增文章
    path('article_create/', views.article_create, name='article_create'),
    # 删除文章
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article_safe_delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    # 更新文章
    path('article_update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:article_id>/', views.post_comment, name='post_comment'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 重置密码
    path('password-reset/', include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
]

# 图片地址
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户修改
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/article/models.py
from django.db import models
# 导入内建的User模型。
from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
# 重定向
from django.urls import reverse

# 博客文章数据模型
class ArticlePost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
#     浏览量
    total_views = models.PositiveIntegerField(default=0)
    
    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return self.title

    # 重定向：获取文章地址
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

my_blog/article/forms.py
# 引入表单类
from django import forms
# 引入文章模型
from .models import ArticlePost

# 写文章的表单类(ModelForm:适合与数据库交互（eg：新建、更新数据库字段）/Form：适合不与数据库交互)
class ArticlePostForm(forms.ModelForm):
    class Meta:
        # 指明数据模型来源
        model = ArticlePost
        # 定义表单包含的字段
        fields = ('title', 'body')

my_blog/article/views.py
from django.http import HttpResponse
from django.shortcuts import render
# 引入markdown模块
import markdown
# 导入数据模型ArticlePost
from .models import ArticlePost
# 引入redirect重定向模块
from django.shortcuts import render, redirect
# 引入HttpResponse
from django.http import HttpResponse
# 引入刚才定义的ArticlePostForm表单类
from .forms import ArticlePostForm
# 引入User模型
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# 引入分页模块
from django.core.paginator import Paginator
# 引入 Q 对象
from django.db.models import Q
from comment.models import Comment


# 文章列表
def article_list(request):
    search = request.GET.get('search')
    order = request.GET.get('order')
    # 用户搜索逻辑
    if search:
        if order == 'total_views':
            # 用 Q对象 进行联合搜索
            article_list = ArticlePost.objects.filter(
                # icontains是不区分大小写的包含，中间用两个下划线隔开/contains区分大小写
                Q(title__icontains=search) |
                Q(body__icontains=search)
            ).order_by('-total_views')
        else:
            article_list = ArticlePost.objects.filter(
                Q(title__icontains=search) |
                Q(body__icontains=search)
            )
    else:
        # 将 search 参数重置为空（search = None）
        search = ''
        # 根据GET请求中查询条件
        # 返回不同排序的对象数组
        if request.GET.get('order') == 'total_views':
            article_list = ArticlePost.objects.all().order_by('-total_views')
            order = 'total_views'
        else:
            article_list = ArticlePost.objects.all()
            order = 'normal'

    # 每页显示 1 篇文章
    paginator = Paginator(article_list, 2)
    # 获取 url 中的页码
    page = request.GET.get('page')
    # 将导航对象相应的页码内容返回给 articles
    articles = paginator.get_page(page)

    context = {'articles': articles, 'order': order}
    # render函数：载入模板，并返回context对象
    return render(request, 'article/list.html', context)


# 文章详情
def article_detail(request, id):
    # 取出相应的文章
    article = ArticlePost.objects.get(id=id)
    # 取出文章评论（filter()可以取出多个满足条件的对象，而get()只能取出1个，注意区分使用）
    comments = Comment.objects.filter(article=id)
    # 浏览量 +1
    article.total_views += 1
    article.save(update_fields=['total_views'])
    # 利用markdown语法渲染成html样式
    md = markdown.Markdown(
        extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 目录扩展
            'markdown.extensions.toc',
        ])
    # 为了能将toc单独提取出来，我们先将Markdown类赋值给一个临时变量md，然后用convert()方法将正文渲染为html页面。通过md.toc将目录传递给模板。
    article.body = md.convert(article.body)
    # 需要传递给模板的对象
    context = {'article': article, 'toc': md.toc, 'comments': comments}
    # 载入模板，并返回context对象
    return render(request, 'article/detail.html', context)


# 文章新增（写文章的视图）
@login_required(login_url='/userprofile/login/')
def article_create(request):
    # 判断用户是否提交数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存数据，但暂时不提交到数据库中
            new_article = article_post_form.save(commit=False)
            # 指定数据库中 id=1 的用户为作者
            # 如果你进行过删除数据表的操作，可能会找不到id=1的用户
            # 此时请重新创建用户，并传入此用户的id
            new_article.author = User.objects.get(id=request.user.id)
            # 将新文章保存到数据库中
            new_article.save()
            # 完成后返回到文章列表
            return redirect("article:article_list")
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")
    # 如果用户请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文
        context = {'article_post_form': article_post_form}
        # 返回模板
        return render(request, 'article/create.html', context)


# 文章删除
@login_required(login_url='/userprofile/login/')
def article_delete(request, id):
    # 根据 id 获取需要删除的文章
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    # 调用.delete()方法删除文章
    article.delete()
    # 完成删除后返回文章列表
    return redirect("article:article_list")


# 文章删除（安全）
@login_required(login_url='/userprofile/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("仅允许post请求")


# 更新文章
@login_required(login_url='/userprofile/login/')
def article_update(request, id):
    """
    更新文章的视图函数
    通过POST方法提交表单，更新titile、body字段
    GET方法进入初始表单页面
    id： 文章的 id
    """

    # 获取需要修改的具体文章对象
    article = ArticlePost.objects.get(id=id)
    # 过滤非作者的用户
    if request.user != article.author:
        return HttpResponse("抱歉，你无权修改这篇文章。")
    # 判断用户是否为 POST 提交表单数据
    if request.method == "POST":
        # 将提交的数据赋值到表单实例中
        article_post_form = ArticlePostForm(data=request.POST)
        # 判断提交的数据是否满足模型的要求
        if article_post_form.is_valid():
            # 保存新写入的 title、body 数据并保存
            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            # 完成后返回到修改后的文章中。需传入文章的 id 值
            return redirect("article:article_detail", id=id)
        # 如果数据不合法，返回错误信息
        else:
            return HttpResponse("表单内容有误，请重新填写。")

    # 如果用户 GET 请求获取数据
    else:
        # 创建表单类实例
        article_post_form = ArticlePostForm()
        # 赋值上下文，将 article 文章对象也传递进去，以便提取旧的内容
        context = {'article': article, 'article_post_form': article_post_form}
        # 将响应返回到模板中
        return render(request, 'article/update.html', context)

my_blog/templates/article/create.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %} {% load staticfiles %}
<!-- 写入 base.html 中定义的 title -->
{% block title %} 写文章 {% endblock title %}
<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 写文章表单 -->
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <!-- 提交文章的表单 -->
            <form method="post" action=".">
                <!-- Django中需要POST数据的地方都必须有csrf_token -->
                {% csrf_token %}
                <!-- 文章标题 -->
                <div class="form-group">
                    <!-- 标签 -->
                    <label for="title">文章标题</label>
                    <!-- 文本框 -->
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

my_blog/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 文章详情 -->
<div class="container">
    <div class="row">
        <!-- 将原有内容嵌套进新的div中 -->
        <div class="col-9">
            <!-- 标题及作者 -->
            <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
            <div class="col-12 alert alert-success">作者：{{ article.author }}</div>
            <!-- 文章正文 -->
            <div class="col-12">
                <!-- Django出于安全的考虑，会将输出的HTML代码进行转义，**这使得article.body中渲染的HTML文本无法正常显示。**管道符|是Django中过滤器的写法，而|safe就类似给article.body贴了一个标签，表示这一段字符不需要进行转义了。-->
                <p>{{ article.body|safe }}</p>
            </div>
            <div class="col-12 alert alert-success">作者：{{ article.author }}
                {% if user == article.author %}
                <a href="#" onclick="confirm_delete()">删除文章</a>
                <a href="{% url 'article:article_update' article.id %}">编辑文章</a>
                {% endif %}
                <form
                        style="display:none;"
                        id="safe_delete"
                        action="{% url 'article:article_safe_delete' article.id %}"
                        method="POST"
                >
                    {% csrf_token %}
                    <button type="submit">发送</button>
                </form>
            </div>
            <div>
                浏览：{{ article.total_views }}
            </div>
        </div>

        <!-- 发表评论 -->
        <hr>
        {% if user.is_authenticated %}
        <div>
            <form
                    action="{% url 'comment:post_comment' article.id %}"
                    method="POST"
            >
                {% csrf_token %}
                <div class="form-group">
                    <label for="body">
                        <strong>
                            我也要发言：
                        </strong>
                    </label>
                    <textarea
                            type="text"
                            class="form-control"
                            id="body"
                            name="body"
                            rows="2"></textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary ">发送</button>
            </form>
        </div>
        <br>
        {% else %}
        <br>
        <h5 class="row justify-content-center">
            请<a href="{% url 'userprofile:login' %}">登录</a>后回复
        </h5>
        <br>
        {% endif %}


        <!-- 显示评论 -->
        <h4>共有{{ comments.count }}条评论</h4>
        <div>
            {% for comment in comments %}
            <hr>
            <p>
                <strong style="color: pink">
                    {{ comment.user }}
                </strong> 于
                <span style="color: green">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
            </p>
            <pre style="font-family: inherit; font-size: 1em;">{{ comment.body }}</pre>
            {% endfor %}
        </div>
    </div>

    <!-- 新增的目录 -->
    <div class="col-3 mt-4">
        <h4><strong>目录</strong></h4>
        <hr>
        <div>
            {{ toc|safe }}
        </div>
    </div>
</div>
</div>

<script>
    // 删除文章的函数
    function confirm_delete() {
        // 调用layer弹窗组件
        layer.open({
            // 弹窗标题
            title: "确认删除",
            // 正文
            content: "确认删除这篇文章吗？",
            // 点击确定按钮后调用的回调函数
            yes: function (index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            },
        })
    }
</script>

{% endblock content %}

my_blog/templates/article/list.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load staticfiles %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
首页
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}

<!-- 定义放置文章标题的div容器 -->
<div class="container">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{% url 'article:article_list' %}">
					最新
				</a>
			</li>
			<li class="breadcrumb-item">
				<a href="{% url 'article:article_list' %}?order=total_views">
					最热
				</a>
			</li>
		</ol>
	</nav>
	<!-- 新增，搜索栏 -->
	<div class="row">
		<div class="col-auto mr-auto">
			<form class="form-inline" >
				<label class="sr-only">content</label>
				<input type="text"
					   class="form-control mb-2 mr-sm-2"
					   name="search"
					   placeholder="搜索文章..."
					   required
				>
			</form>
		</div>
	</div>

	<!-- 新增，搜索提示语 -->
	{% if search %}
	{% if articles %}
	<h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
	<hr>
	{% else %}
	<h4>暂无<span style="color: red">"{{ search }}"</span>有关的文章。</h4>
	<hr>
	{% endif %}
	{% endif %}
	<div class="row mt-2">

		{% for article in articles %}
		<!-- 文章内容 -->
		<div class="col-4 mb-4">
			<!-- 卡片容器 -->
			<div class="card h-100">
				<!-- 标题 -->
				<h4 class="card-header">{{ article.title }}</h4>
				<!-- 摘要 -->
				<div class="card-body">
					<p class="card-text">{{ article.body|slice:'100' }}...</p>
				</div>
				<!-- 注脚 -->
				<div class="card-footer">
					<a href="{% url 'article:article_detail' article.id %}" class="btn btn-primary">阅读本文</a>
					<!-- 显示浏览量 -->
					<span>
						<small class="col align-self-end" style="color: gray;">
							浏览: {{ article.total_views }}
						</small>
					</span>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>

	<!-- 页码导航 -->
	<div class="pagination row">
		<div class="m-auto">
        <span class="step-links">
            <!-- 如果不是第一页，则显示上翻按钮 -->
            {% if articles.has_previous %}
                <a href="?page=1&order={{ order }}" class="btn btn-success">
                    &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ articles.previous_page_number }}&order={{ order }}"
				   class="btn btn-secondary"
				>
                    {{ articles.previous_page_number }}
                </a>
            {% endif %}

			<!-- 当前页面 -->
            <span class="current btn btn-danger btn-lg">
                {{ articles.number }}
            </span>

			<!-- 如果不是最末页，则显示下翻按钮 -->
            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}&order={{ order }}"
				   class="btn btn-secondary"
				>
                    {{ articles.next_page_number }}
                </a>
                <span>...</span>
                <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}"
				   class="btn btn-success"
				>
                    {{ articles.paginator.num_pages }} &raquo;
                </a>
            {% endif %}
        </span>
		</div>
	</div>
</div>
{% endblock content %}

my_blog/templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <br>
      <form method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
          <label for="title">文章标题</label>
          <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
          <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
        </div>
        <div class="form-group">
          <label for="body">文章正文</label>
          <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
          <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">完成</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}