my_blog/article/urls.py
# 引入path
from django.urls import path
# 引入views.py
from . import views

# 正在部署的应用的名称
app_name = 'article'

urlpatterns = [
    # path函数将url映射到视图
    # 左：请求地址/中：视图方法/右：网页内部调用
    path('article_list/',views.article_list,name='article_list'),
    # 文章详情
    path('article_detail/<int:id>/', views.article_detail, name='article_detail'),
    # 新增文章
    path('article_create/', views.article_create, name='article_create'),
    # 删除文章
    path('article_delete/<int:id>/', views.article_delete, name='article_delete'),
    # 安全删除文章
    path('article_safe_delete/<int:id>/',views.article_safe_delete,name='article_safe_delete'),
    # 更新文章
    path('article_update/<int:id>/', views.article_update, name='article_update'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 新增代码，配置app的url
    path('article/', include('article.urls', namespace='article')),
    # 用户管理
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # 重置密码
    path('password-reset/', include('password_reset.urls')),
    # 评论
    path('comment/', include('comment.urls', namespace='comment')),
]

# 图片地址
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    # 用户登录
    path('login/', views.user_login, name='login'),
    # 用户退出
    path('logout/', views.user_logout, name='logout'),
    # 用户注册
    path('register/', views.user_register, name='register'),
    # 用户删除
    path('delete/<int:id>/', views.user_delete, name='delete'),
    # 用户修改
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

my_blog/templates/base.html
<!--
    载入静态文件
    使用 Django 3 学习的读者改为 {% load static %}
-->
{% load staticfiles %}

<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
  <!-- 网站采用的字符编码 -->
  <meta charset="utf-8">
  <!-- 预留网站标题的位置 -->
  <title>{% block title %}{% endblock %}</title>
  <!-- 引入bootstrap的css文件 -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <!-- 引入monikai.css(高亮) -->
  <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}
<!-- bootstrap.js 依赖 jquery.js 和popper.js，因此在这里引入 -->
<script src="{% static 'jquery/jquery-3.6.1.min.js' %}"></script>
<!-- 引入layer.js -->
<script src="{% static 'layui/layui.js' %}"></script>

<!--
    popper.js 采用 cdn 远程引入，意思是你不需要把它下载到本地。
    在实际的开发中推荐静态文件尽量都使用 cdn 的形式。
    教程采用本地引入是为了让读者了解静态文件本地部署的流程。
-->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- 引入bootstrap的js文件 -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

my_blog/templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<div>
    <br><br><br>
</div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.dusaiphoto.com 2018</p>
    </div>
</footer>

my_blog/templates/header.html
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">

        <!-- 导航栏商标 -->
        <a class="navbar-brand" href="#">我的博客</a>

        <!-- 导航入口 -->
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">写文章</a>
                </li>
                <!-- 条目 -->
                <li class="nav-item">
                    <!-- article:urls.py中app的名称，article_list:具体路由地址-->
                    <a class="nav-link" href="{% url 'article:article_list' %}">文章</a>
                </li>
            </ul>
            <!-- Django的 if 模板语句 -->
            {% if user.is_authenticated %}
            <!-- 如果用户已经登录，则显示用户名下拉框 -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>个人信息</a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                    <a class="dropdown-item" href='{% url "userprofile:logout" %}'>退出登录</a>                </div>
            </li>
            <!-- 如果用户未登录，则显示 “登录” -->
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'userprofile:login' %}">登录</a>
            </li>
            <!-- if 语句在这里结束 -->
            {% endif %}
            {% if user.is_authenticated %}
            <form
                    style="display:none;"
                    id="user_delete"
                    action="{% url 'userprofile:delete' user.id %}"
                    method="POST"
            >
                {% csrf_token %}
                <button type="submit">发送</button>
            </form>
            <script>
                function user_delete() {
                    // 调用layer弹窗组件
                    layer.open({
                        title: "确认删除",
                        content: "确认删除用户资料吗？",
                        yes: function(index, layero) {
                            $('form#user_delete button').click();
                            layer.close(index);
                        },
                    })
                }
            </script>
            {% endif %}
        </div>

    </div>
</nav>